import { test, expect } from '@playwright/test';

async function login(page,email){await page.goto('/login');await page.locator('input[type="email"]').fill(email);await page.locator('input[type="password"]').fill('password');await page.getByRole('button',{name:/sign in/i}).click();await expect(page).toHaveURL(/dashboard/);}
function captureErrors(page){const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('pageerror',e=>errors.push(e.message));return errors;}

test.describe('professional HRM workspaces',()=>{
 test('admin can open every operational workspace without runtime errors',async({page},testInfo)=>{test.skip(testInfo.project.name!=='desktop');const errors=captureErrors(page);await login(page,'admin@gmail.com');for(const[path,title]of[['/talent','Talent & Lifecycle'],['/employee-services','Employee Services'],['/operations','Operations Center'],['/compensation','Compensation'],['/administration','HR Administration'],['/documents','Employee Documents'],['/my-hr','My HR']]){await page.goto(path);await expect(page.getByRole('heading',{name:title})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}await page.screenshot({path:'test-results/admin-workspaces.png',fullPage:true});expect(errors).toEqual([]);});
 test('employee self service is responsive and hides administrative navigation',async({page})=>{const errors=captureErrors(page);await login(page,'employee@gmail.com');await page.goto('/my-hr');await expect(page.getByRole('heading',{name:'My HR'})).toBeVisible();await expect(page.getByText('Compensation',{exact:true})).toHaveCount(0);await expect(page.getByText('Administration',{exact:true})).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`test-results/my-hr-${test.info().project.name}.png`,fullPage:true});expect(errors).toEqual([]);});
});
