<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('job_requisitions', function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('department_id')->constrained()->restrictOnDelete();$t->foreignId('position_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->unsignedSmallInteger('vacancies')->default(1);$t->text('description');$t->text('requirements')->nullable();$t->decimal('salary_min',12,2)->nullable();$t->decimal('salary_max',12,2)->nullable();$t->enum('employment_type',['full-time','part-time','contract','intern']);$t->enum('status',['draft','pending_approval','open','closed','cancelled'])->default('draft');$t->date('closing_date')->nullable();$t->foreignId('requested_by')->constrained('users')->restrictOnDelete();$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('candidates', function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('phone')->nullable();$t->string('source')->nullable();$t->string('resume_path')->nullable();$t->string('national_id')->nullable();$t->json('skills')->nullable();$t->decimal('experience_years',5,2)->default(0);$t->json('education')->nullable();$t->timestamps();});
  Schema::create('job_applications', function(Blueprint $t){$t->id();$t->foreignId('job_requisition_id')->constrained()->cascadeOnDelete();$t->foreignId('candidate_id')->constrained()->cascadeOnDelete();$t->enum('stage',['applied','screening','shortlisted','interview','offer','hired','rejected','withdrawn'])->default('applied');$t->decimal('rating',4,2)->nullable();$t->text('notes')->nullable();$t->foreignId('assigned_recruiter')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['job_requisition_id','candidate_id']);});
  Schema::create('interviews', function(Blueprint $t){$t->id();$t->foreignId('job_application_id')->constrained()->cascadeOnDelete();$t->enum('type',['phone','video','onsite','technical','hr','final']);$t->timestamp('scheduled_at');$t->unsignedSmallInteger('duration_minutes')->default(60);$t->string('location_or_link')->nullable();$t->enum('status',['scheduled','completed','cancelled','no_show'])->default('scheduled');$t->decimal('score',5,2)->nullable();$t->text('feedback')->nullable();$t->timestamps();});
  Schema::create('interview_panel', function(Blueprint $t){$t->id();$t->foreignId('interview_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->boolean('is_lead')->default(false);$t->unique(['interview_id','user_id']);});
  Schema::create('onboarding_cases', function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->date('start_date');$t->date('target_completion_date')->nullable();$t->enum('status',['not_started','in_progress','completed','cancelled'])->default('not_started');$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  Schema::create('onboarding_tasks', function(Blueprint $t){$t->id();$t->foreignId('onboarding_case_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->date('due_date')->nullable();$t->enum('status',['pending','in_progress','completed','waived'])->default('pending');$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('performance_cycles', function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->date('starts_on');$t->date('ends_on');$t->enum('status',['draft','active','review','closed'])->default('draft');$t->timestamps();});
  Schema::create('performance_goals', function(Blueprint $t){$t->id();$t->foreignId('performance_cycle_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->decimal('weight',5,2);$t->decimal('target_value',12,2)->nullable();$t->decimal('actual_value',12,2)->nullable();$t->enum('status',['draft','active','completed','cancelled'])->default('draft');$t->timestamps();});
  Schema::create('performance_reviews', function(Blueprint $t){$t->id();$t->foreignId('performance_cycle_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->foreignId('reviewer_id')->constrained('users')->restrictOnDelete();$t->enum('review_type',['self','manager','peer','hr'])->default('manager');$t->decimal('score',5,2)->nullable();$t->json('ratings')->nullable();$t->text('strengths')->nullable();$t->text('improvements')->nullable();$t->text('comments')->nullable();$t->enum('status',['draft','submitted','acknowledged'])->default('draft');$t->timestamps();$t->unique(['performance_cycle_id','employee_id','reviewer_id','review_type'],'performance_review_unique');});
  Schema::create('training_courses', function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('provider')->nullable();$t->decimal('cost',12,2)->default(0);$t->unsignedSmallInteger('duration_hours')->default(0);$t->boolean('is_mandatory')->default(false);$t->date('valid_until')->nullable();$t->timestamps();});
  Schema::create('training_enrollments', function(Blueprint $t){$t->id();$t->foreignId('training_course_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->enum('status',['enrolled','in_progress','completed','failed','cancelled'])->default('enrolled');$t->decimal('score',5,2)->nullable();$t->timestamp('completed_at')->nullable();$t->string('certificate_path')->nullable();$t->date('certificate_expires_at')->nullable();$t->timestamps();$t->unique(['training_course_id','employee_id']);});
  Schema::create('offboarding_cases', function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->enum('separation_type',['resignation','termination','retirement','redundancy','death','contract_end']);$t->date('notice_date');$t->date('last_working_date');$t->text('reason')->nullable();$t->enum('status',['initiated','clearance','settlement','completed','cancelled'])->default('initiated');$t->foreignId('owner_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('exit_interview_at')->nullable();$t->text('exit_feedback')->nullable();$t->timestamps();});
  Schema::create('offboarding_clearances', function(Blueprint $t){$t->id();$t->foreignId('offboarding_case_id')->constrained()->cascadeOnDelete();$t->string('area');$t->foreignId('approver_id')->nullable()->constrained('users')->nullOnDelete();$t->enum('status',['pending','cleared','blocked','waived'])->default('pending');$t->text('notes')->nullable();$t->timestamp('cleared_at')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['offboarding_clearances','offboarding_cases','training_enrollments','training_courses','performance_reviews','performance_goals','performance_cycles','onboarding_tasks','onboarding_cases','interview_panel','interviews','job_applications','candidates','job_requisitions'] as $table) Schema::dropIfExists($table);}
};
