<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
Schema::create('expense_claims',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->string('claim_number')->unique();$t->string('category');$t->date('expense_date');$t->decimal('amount',12,2);$t->string('currency',3)->default('BDT');$t->text('description');$t->string('receipt_path')->nullable();$t->enum('status',['draft','submitted','approved','rejected','reimbursed'])->default('draft');$t->foreignId('approved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reimbursed_at')->nullable();$t->timestamps();});
Schema::create('assets',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('asset_tag')->unique();$t->string('name');$t->string('category');$t->string('serial_number')->nullable()->unique();$t->date('purchase_date')->nullable();$t->decimal('purchase_cost',12,2)->nullable();$t->date('warranty_expires_at')->nullable();$t->enum('status',['available','assigned','maintenance','retired','lost'])->default('available');$t->text('notes')->nullable();$t->timestamps();});
Schema::create('asset_assignments',function(Blueprint $t){$t->id();$t->foreignId('asset_id')->constrained()->restrictOnDelete();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->date('assigned_at');$t->date('expected_return_at')->nullable();$t->date('returned_at')->nullable();$t->enum('condition_on_issue',['new','good','fair','damaged'])->default('good');$t->string('condition_on_return')->nullable();$t->foreignId('assigned_by')->constrained('users')->restrictOnDelete();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('benefit_plans',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->enum('type',['insurance','provident_fund','gratuity','medical','transport','meal','other']);$t->decimal('employee_contribution',12,2)->default(0);$t->decimal('employer_contribution',12,2)->default(0);$t->date('effective_from');$t->date('effective_to')->nullable();$t->json('rules')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('benefit_enrollments',function(Blueprint $t){$t->id();$t->foreignId('benefit_plan_id')->constrained()->cascadeOnDelete();$t->foreignId('employee_id')->constrained()->cascadeOnDelete();$t->date('enrolled_at');$t->date('ended_at')->nullable();$t->enum('status',['active','suspended','ended'])->default('active');$t->json('dependents')->nullable();$t->timestamps();$t->unique(['benefit_plan_id','employee_id']);});
Schema::create('grievance_cases',function(Blueprint $t){$t->id();$t->foreignId('employee_id')->constrained()->restrictOnDelete();$t->string('case_number')->unique();$t->enum('type',['grievance','disciplinary','harassment','safety','ethics','other']);$t->string('subject');$t->text('description');$t->enum('confidentiality',['standard','confidential','anonymous'])->default('confidential');$t->enum('status',['open','investigating','hearing','resolved','closed','appealed'])->default('open');$t->foreignId('case_owner')->nullable()->constrained('users')->nullOnDelete();$t->text('resolution')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
Schema::create('grievance_actions',function(Blueprint $t){$t->id();$t->foreignId('grievance_case_id')->constrained()->cascadeOnDelete();$t->string('action');$t->text('notes')->nullable();$t->foreignId('performed_by')->constrained('users')->restrictOnDelete();$t->timestamp('performed_at');$t->timestamps();});
Schema::create('announcements',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('title');$t->text('body');$t->enum('priority',['normal','important','urgent'])->default('normal');$t->json('audience')->nullable();$t->timestamp('published_at')->nullable();$t->timestamp('expires_at')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('announcement_reads',function(Blueprint $t){$t->id();$t->foreignId('announcement_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamp('read_at');$t->unique(['announcement_id','user_id']);});
Schema::create('surveys',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->boolean('is_anonymous')->default(false);$t->timestamp('opens_at');$t->timestamp('closes_at');$t->enum('status',['draft','active','closed'])->default('draft');$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('survey_questions',function(Blueprint $t){$t->id();$t->foreignId('survey_id')->constrained()->cascadeOnDelete();$t->text('question');$t->enum('type',['text','single_choice','multiple_choice','rating','boolean']);$t->json('options')->nullable();$t->boolean('is_required')->default(true);$t->unsignedSmallInteger('sequence');$t->timestamps();});
Schema::create('survey_responses',function(Blueprint $t){$t->id();$t->foreignId('survey_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('anonymous_token')->nullable();$t->json('answers');$t->timestamp('submitted_at');$t->timestamps();});
Schema::create('data_imports',function(Blueprint $t){$t->id();$t->string('type');$t->string('file_path');$t->enum('status',['queued','processing','completed','failed'])->default('queued');$t->unsignedInteger('total_rows')->default(0);$t->unsignedInteger('processed_rows')->default(0);$t->unsignedInteger('failed_rows')->default(0);$t->json('errors')->nullable();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
Schema::create('integration_webhooks',function(Blueprint $t){$t->id();$t->foreignId('company_id')->nullable()->constrained()->cascadeOnDelete();$t->string('name');$t->string('url');$t->string('secret');$t->json('events');$t->boolean('is_active')->default(true);$t->timestamp('last_triggered_at')->nullable();$t->timestamps();});
}public function down():void{foreach(['integration_webhooks','data_imports','survey_responses','survey_questions','surveys','announcement_reads','announcements','grievance_actions','grievance_cases','benefit_enrollments','benefit_plans','asset_assignments','assets','expense_claims']as$t)Schema::dropIfExists($t);}};
