<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class EmployeeServicesController extends Controller{
 public function overview(Request$r){$employeeId=$r->user()->employee?->id;$canManage=$r->user()->hasPermission('expense.manage');return response()->json([
  'expenses'=>DB::table('expense_claims as x')->join('employees as e','e.id','=','x.employee_id')->join('users as u','u.id','=','e.user_id')->when(!$canManage,fn($q)=>$q->where('x.employee_id',$employeeId??0))->select('x.*','u.name as employee_name')->orderByDesc('x.id')->limit(100)->get(),
  'assets'=>DB::table('assets')->orderByDesc('id')->limit(100)->get(),
  'asset_assignments'=>DB::table('asset_assignments as aa')->join('assets as a','a.id','=','aa.asset_id')->join('employees as e','e.id','=','aa.employee_id')->join('users as u','u.id','=','e.user_id')->select('aa.*','a.name as asset_name','a.asset_tag','u.name as employee_name')->orderByDesc('aa.id')->limit(100)->get(),
  'benefits'=>DB::table('benefit_plans')->where('is_active',true)->orderBy('name')->get(),
  'benefit_enrollments'=>DB::table('benefit_enrollments as b')->join('benefit_plans as p','p.id','=','b.benefit_plan_id')->join('employees as e','e.id','=','b.employee_id')->join('users as u','u.id','=','e.user_id')->select('b.*','p.name as benefit_name','u.name as employee_name')->orderByDesc('b.id')->limit(100)->get(),
  'grievances'=>DB::table('grievance_cases')->when(!$r->user()->hasPermission('grievance.manage'),fn($q)=>$q->where('employee_id',$employeeId??0))->orderByDesc('id')->limit(100)->get(),
  'announcements'=>DB::table('announcements')->where(fn($q)=>$q->whereNull('published_at')->orWhere('published_at','<=',now()))->orderByDesc('id')->limit(30)->get(),
  'surveys'=>DB::table('surveys')->orderByDesc('id')->limit(30)->get(),
 ]);}
 public function expenses(Request $r){$q=DB::table('expense_claims');if(!$r->user()->hasPermission('expense.manage'))$q->where('employee_id',$r->user()->employee?->id??0);return $q->orderByDesc('id')->paginate(20);}
 public function storeExpense(Request $r){abort_unless($r->user()->employee,404,'Employee record not found');$d=$r->validate(['category'=>'required|string|max:100','expense_date'=>'required|date|before_or_equal:today','amount'=>'required|numeric|min:0.01','description'=>'required|string','receipt_path'=>'nullable|string']);$d+=['employee_id'=>$r->user()->employee->id,'claim_number'=>'EXP-'.now()->format('Ymd').'-'.Str::upper(Str::random(6)),'currency'=>'BDT','status'=>'submitted'];return DB::transaction(function()use($r,$d){$id=DB::table('expense_claims')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);$approver=app(\App\Services\ApprovalRouter::class)->firstApprover('expense',$r->user()->employee);DB::table('approval_requests')->insert(['approvable_type'=>'App\\Models\\ExpenseClaim','approvable_id'=>$id,'step'=>1,'requested_by'=>$r->user()->id,'approver_id'=>$approver,'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table('expense_claims')->find($id),201);});}
 public function expenseStatus(Request $r,int$id){$d=$r->validate(['status'=>'required|in:approved,rejected,reimbursed']);$d['approved_by']=$r->user()->id;if($d['status']==='reimbursed')$d['reimbursed_at']=now();return $this->update('expense_claims',$id,$d);}
 public function assets(Request$r){return DB::table('assets')->when($r->status,fn($q,$v)=>$q->where('status',$v))->paginate(30);}
 public function storeAsset(Request$r){return $this->insert('assets',$r->validate(['company_id'=>'nullable|exists:companies,id','asset_tag'=>'required|string|unique:assets','name'=>'required|string','category'=>'required|string','serial_number'=>'nullable|string|unique:assets','purchase_date'=>'nullable|date','purchase_cost'=>'nullable|numeric|min:0','warranty_expires_at'=>'nullable|date','notes'=>'nullable|string']));}
 public function assignAsset(Request$r){$d=$r->validate(['asset_id'=>'required|exists:assets,id','employee_id'=>'required|exists:employees,id','assigned_at'=>'required|date','expected_return_at'=>'nullable|date|after_or_equal:assigned_at','condition_on_issue'=>'required|in:new,good,fair,damaged','notes'=>'nullable|string']);abort_unless(DB::table('assets')->where('id',$d['asset_id'])->where('status','available')->exists(),422,'Asset is not available');$d['assigned_by']=$r->user()->id;return DB::transaction(function()use($d){$res=$this->insert('asset_assignments',$d);DB::table('assets')->where('id',$d['asset_id'])->update(['status'=>'assigned','updated_at'=>now()]);return$res;});}
 public function returnAsset(Request$r,int$id){$d=$r->validate(['returned_at'=>'required|date','condition_on_return'=>'required|string','notes'=>'nullable|string']);$row=DB::table('asset_assignments')->find($id);abort_unless($row&&!$row->returned_at,422,'Active assignment not found');return DB::transaction(function()use($id,$d,$row){$this->update('asset_assignments',$id,$d);DB::table('assets')->where('id',$row->asset_id)->update(['status'=>'available','updated_at'=>now()]);return response()->json(['message'=>'Asset returned']);});}
 public function storeBenefitPlan(Request$r){$d=$r->validate(['company_id'=>'nullable|exists:companies,id','name'=>'required|string','type'=>'required|in:insurance,provident_fund,gratuity,medical,transport,meal,other','employee_contribution'=>'sometimes|numeric|min:0','employer_contribution'=>'sometimes|numeric|min:0','effective_from'=>'required|date','effective_to'=>'nullable|date|after_or_equal:effective_from','rules'=>'nullable|array']);return$this->insert('benefit_plans',$d);}
 public function enrollBenefit(Request$r){$d=$r->validate(['benefit_plan_id'=>'required|exists:benefit_plans,id','employee_id'=>'required|exists:employees,id','enrolled_at'=>'required|date','dependents'=>'nullable|array']);return$this->insert('benefit_enrollments',$d);}
 public function grievances(Request$r){$q=DB::table('grievance_cases');if(!$r->user()->hasPermission('grievance.manage'))$q->where('employee_id',$r->user()->employee?->id??0);return$q->orderByDesc('id')->paginate(20);}
 public function storeGrievance(Request$r){abort_unless($r->user()->employee,404,'Employee record not found');$d=$r->validate(['type'=>'required|in:grievance,disciplinary,harassment,safety,ethics,other','subject'=>'required|string','description'=>'required|string','confidentiality'=>'sometimes|in:standard,confidential,anonymous']);$d+=['employee_id'=>$r->user()->employee->id,'case_number'=>'CASE-'.now()->format('Ymd').'-'.Str::upper(Str::random(6))];return$this->insert('grievance_cases',$d);}
 public function grievanceAction(Request$r,int$id){$d=$r->validate(['action'=>'required|string','notes'=>'nullable|string','status'=>'nullable|in:open,investigating,hearing,resolved,closed,appealed','resolution'=>'nullable|string']);abort_unless(DB::table('grievance_cases')->where('id',$id)->exists(),404);return DB::transaction(function()use($r,$id,$d){DB::table('grievance_actions')->insert(['grievance_case_id'=>$id,'action'=>$d['action'],'notes'=>$d['notes']??null,'performed_by'=>$r->user()->id,'performed_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);$up=array_filter(['status'=>$d['status']??null,'resolution'=>$d['resolution']??null],fn($v)=>$v!==null);if(($up['status']??null)==='resolved')$up['resolved_at']=now();if($up)DB::table('grievance_cases')->where('id',$id)->update($up+['updated_at'=>now()]);return response()->json(['message'=>'Case action recorded']);});}
 public function announcements(Request$r){return DB::table('announcements')->where(fn($q)=>$q->whereNull('published_at')->orWhere('published_at','<=',now()))->where(fn($q)=>$q->whereNull('expires_at')->orWhere('expires_at','>',now()))->orderByDesc('published_at')->paginate(20);}
 public function storeAnnouncement(Request$r){$d=$r->validate(['company_id'=>'nullable|exists:companies,id','title'=>'required|string','body'=>'required|string','priority'=>'sometimes|in:normal,important,urgent','audience'=>'nullable|array','published_at'=>'nullable|date','expires_at'=>'nullable|date|after:published_at']);$d['created_by']=$r->user()->id;return$this->insert('announcements',$d);}
 public function readAnnouncement(Request$r,int$id){abort_unless(DB::table('announcements')->where('id',$id)->exists(),404);DB::table('announcement_reads')->updateOrInsert(['announcement_id'=>$id,'user_id'=>$r->user()->id],['read_at'=>now()]);return response()->noContent();}
 public function storeSurvey(Request$r){$d=$r->validate(['company_id'=>'nullable|exists:companies,id','title'=>'required|string','description'=>'nullable|string','is_anonymous'=>'sometimes|boolean','opens_at'=>'required|date','closes_at'=>'required|date|after:opens_at','status'=>'sometimes|in:draft,active','questions'=>'required|array|min:1','questions.*.question'=>'required|string','questions.*.type'=>'required|in:text,single_choice,multiple_choice,rating,boolean','questions.*.options'=>'nullable|array','questions.*.is_required'=>'sometimes|boolean']);$d['created_by']=$r->user()->id;return DB::transaction(function()use($d){$qs=$d['questions'];unset($d['questions']);$id=DB::table('surveys')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);foreach($qs as$i=>$q){if(isset($q['options']))$q['options']=json_encode($q['options']);DB::table('survey_questions')->insert($q+['survey_id'=>$id,'sequence'=>$i+1,'created_at'=>now(),'updated_at'=>now()]);}return response()->json(['id'=>$id],201);});}
 public function respondSurvey(Request$r,int$id){$survey=DB::table('surveys')->find($id);abort_unless($survey&&$survey->status==='active'&&now()->between($survey->opens_at,$survey->closes_at),422,'Survey is not active');$d=$r->validate(['answers'=>'required|array']);if(!$survey->is_anonymous)abort_if(DB::table('survey_responses')->where('survey_id',$id)->where('user_id',$r->user()->id)->exists(),422,'Survey already submitted');$required=DB::table('survey_questions')->where('survey_id',$id)->where('is_required',true)->pluck('id')->map(fn($x)=>(string)$x);abort_if($required->contains(fn($qid)=>!array_key_exists($qid,$d['answers'])&&!array_key_exists((int)$qid,$d['answers'])),422,'All required questions must be answered');return$this->insert('survey_responses',['survey_id'=>$id,'user_id'=>$survey->is_anonymous?null:$r->user()->id,'anonymous_token'=>$survey->is_anonymous?Str::uuid():null,'answers'=>$d['answers'],'submitted_at'=>now()]);}
 private function insert(string$t,array$d){foreach($d as$k=>$v)if(is_array($v))$d[$k]=json_encode($v);$id=DB::table($t)->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table($t)->find($id),201);}private function update(string$t,int$id,array$d){abort_unless(DB::table($t)->where('id',$id)->exists(),404);DB::table($t)->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(DB::table($t)->find($id));}
}
