<?php
namespace App\Http\Controllers;
use App\Models\ApprovalRequest;use App\Models\Employee;use App\Models\Leave;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;
class OperationsController extends Controller{
 public function approvals(Request$r){$q=ApprovalRequest::with(['requester','approver'])->orderByDesc('id');if(!$r->user()->hasPermission('approval.manage'))$q->where('approver_id',$r->user()->id);return$q->paginate(30);}
 public function act(Request$r,ApprovalRequest$approvalRequest){$d=$r->validate(['status'=>'required|in:approved,rejected','comments'=>'nullable|string']);abort_unless($approvalRequest->status==='pending',422,'Approval already processed');abort_unless($r->user()->hasPermission('approval.manage')||$approvalRequest->approver_id===$r->user()->id,403);$payload=['approval_id'=>$approvalRequest->id,'status'=>$d['status'],'comments'=>$d['comments']??null];DB::transaction(function()use($r,$d,$approvalRequest,$payload){$target=$approvalRequest->approvable;if($target instanceof Leave&&$d['status']==='approved')app(\App\Services\LeaveBalanceService::class)->consume($target,$r->user()->id);$approvalRequest->update($d+['approver_id'=>$r->user()->id,'acted_at'=>now()]);if($target&&in_array($target->getTable(),['leaves','expense_claims'],true))$target->update(['status'=>$d['status'],'approved_by'=>$r->user()->id]);$this->notify($approvalRequest->requested_by,'approval.updated',$payload);});app(\App\Services\IntegrationDispatcher::class)->dispatch('approval.updated',$payload);return$approvalRequest->fresh();}
 public function notifications(Request$r){return$r->user()->notifications()->latest()->paginate(30);}
 public function readNotification(Request$r,string$id){$n=$r->user()->notifications()->findOrFail($id);$n->markAsRead();return response()->noContent();}
 public function export(Request$r,string$type){abort_unless(in_array($type,['employees','attendance','payroll'],true),404);$filename=$type.'-'.now()->format('Ymd-His').'.csv';return response()->streamDownload(function()use($type){$out=fopen('php://output','w');if($type==='employees'){$rows=DB::table('employees as e')->join('users as u','u.id','=','e.user_id')->leftJoin('departments as d','d.id','=','e.department_id')->select('u.employee_id','u.name','u.email','u.phone','d.name as department','e.employment_type','e.joining_date','e.salary')->get();$headers=['employee_id','name','email','phone','department','employment_type','joining_date','salary'];}elseif($type==='attendance'){$rows=DB::table('attendances as a')->join('employees as e','e.id','=','a.employee_id')->join('users as u','u.id','=','e.user_id')->select('u.employee_id','u.name','a.date','a.check_in','a.check_out','a.status','a.worked_minutes','a.overtime_minutes')->get();$headers=['employee_id','name','date','check_in','check_out','status','worked_minutes','overtime_minutes'];}else{$rows=DB::table('payroll_items as p')->join('payroll_runs as r','r.id','=','p.payroll_run_id')->join('employees as e','e.id','=','p.employee_id')->join('users as u','u.id','=','e.user_id')->select('r.name as payroll_run','u.employee_id','u.name','p.gross_earnings','p.tax_deduction','p.provident_fund_employee','p.net_pay')->get();$headers=['payroll_run','employee_id','name','gross_earnings','tax_deduction','provident_fund_employee','net_pay'];}fputcsv($out,$headers);foreach($rows as$row)fputcsv($out,array_map(fn($h)=>$row->$h,$headers));fclose($out);},$filename,['Content-Type'=>'text/csv']);}
 public function imports(){return response()->json(DB::table('data_imports')->latest()->limit(100)->get()->map(fn($x)=>tap($x,fn($y)=>$y->errors=json_decode($y->errors??'[]',true)?:[])));}
 public function importEmployees(Request$r){$r->validate(['file'=>'required|file|mimes:csv,txt|max:5120']);$importId=DB::table('data_imports')->insertGetId(['type'=>'employees','file_path'=>$r->file('file')->getClientOriginalName(),'status'=>'processing','created_by'=>$r->user()->id,'created_at'=>now(),'updated_at'=>now()]);$handle=fopen($r->file('file')->getRealPath(),'r');$processed=0;$errors=[];try{$headers=fgetcsv($handle);$required=['employee_id','name','email','phone','joining_date'];if(array_diff($required,$headers?:[]))throw new \RuntimeException('Required columns: '.implode(', ',$required));DB::beginTransaction();try{while(($row=fgetcsv($handle))!==false){$data=array_combine($headers,$row);try{if($data===false)throw new \RuntimeException('Column count does not match the header');if(DB::table('users')->where('email',$data['email'])->orWhere('employee_id',$data['employee_id'])->exists())throw new \RuntimeException('Duplicate email or employee ID');$userId=DB::table('users')->insertGetId(['name'=>$data['name'],'email'=>$data['email'],'phone'=>$data['phone'],'employee_id'=>$data['employee_id'],'password'=>Hash::make(Str::password(16)),'role_id'=>DB::table('roles')->where('slug','employee')->value('id'),'hire_date'=>$data['joining_date'],'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);DB::table('employees')->insert(['user_id'=>$userId,'joining_date'=>$data['joining_date'],'employment_type'=>$data['employment_type']??'full-time','salary'=>(float)($data['salary']??0),'created_at'=>now(),'updated_at'=>now()]);$processed++;}catch(\Throwable$e){$errors[]=['row'=>$processed+count($errors)+2,'message'=>$e->getMessage()];}}DB::commit();}catch(\Throwable$e){DB::rollBack();throw$e;}DB::table('data_imports')->where('id',$importId)->update(['status'=>'completed','total_rows'=>$processed+count($errors),'processed_rows'=>$processed,'failed_rows'=>count($errors),'errors'=>json_encode($errors),'updated_at'=>now()]);}catch(\Throwable$e){DB::table('data_imports')->where('id',$importId)->update(['status'=>'failed','processed_rows'=>$processed,'failed_rows'=>count($errors),'errors'=>json_encode(array_merge($errors,[['message'=>$e->getMessage()]])),'updated_at'=>now()]);abort(422,$e->getMessage());}finally{fclose($handle);}return response()->json(['processed'=>$processed,'failed'=>count($errors),'errors'=>$errors]);}
 private function notify(int$userId,string$type,array$data):void{DB::table('notifications')->insert(['id'=>(string)Str::uuid(),'type'=>$type,'notifiable_type'=>'App\\Models\\User','notifiable_id'=>$userId,'data'=>json_encode($data),'created_at'=>now(),'updated_at'=>now()]);}
}
