<?php
namespace App\Http\Controllers;
use App\Services\IntegrationDispatcher;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class OrganizationController extends Controller{
 public function overview(){return response()->json(['companies'=>DB::table('companies')->orderBy('name')->get()->map(fn($c)=>tap($c,fn($x)=>$x->settings=json_decode($x->settings??'{}',true)?:[])),'branches'=>DB::table('branches')->orderBy('name')->get(),'shifts'=>DB::table('shifts')->orderBy('name')->get(),'holidays'=>DB::table('holidays')->orderByDesc('date')->limit(100)->get(),'leave_types'=>DB::table('leave_types')->orderBy('name')->get(),'roles'=>DB::table('roles')->orderBy('name')->get()->map(fn($r)=>tap($r,fn($x)=>$x->permissions=json_decode($x->permissions??'[]',true)?:[])),'approval_workflows'=>DB::table('approval_workflows')->orderBy('module')->get(),'integrations'=>DB::table('integration_webhooks')->select('id','company_id','name','url','events','is_active','last_triggered_at')->get()->map(fn($x)=>tap($x,fn($y)=>$y->events=json_decode($y->events,true)?:[])),'integration_deliveries'=>DB::table('integration_deliveries as d')->join('integration_webhooks as w','w.id','=','d.integration_webhook_id')->select('d.id','d.event','d.delivery_id','d.attempt','d.status','d.response_status','d.error','d.created_at','w.name as integration_name')->latest('d.id')->limit(100)->get(),'permission_catalog'=>config('hrm.permissions')]);}
 public function retryIntegration(int$id,IntegrationDispatcher$dispatcher){return response()->json($dispatcher->retry($id),201);}
 public function storeApprovalWorkflow(Request$r){$d=$r->validate(['company_id'=>'nullable|exists:companies,id','name'=>'required|string','module'=>'required|in:leave,expense,payroll,requisition,onboarding,offboarding','steps'=>'required|array|min:1','steps.*.approver_type'=>'required|in:manager,role,user','steps.*.role_id'=>'nullable|exists:roles,id','steps.*.user_id'=>'nullable|exists:users,id']);return DB::transaction(function()use($d){$steps=$d['steps'];unset($d['steps']);$id=DB::table('approval_workflows')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);foreach($steps as$i=>$step)DB::table('approval_workflow_steps')->insert($step+['approval_workflow_id'=>$id,'sequence'=>$i+1,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['id'=>$id],201);});}
 public function storeIntegration(Request$r){$d=$r->validate(['company_id'=>'nullable|exists:companies,id','name'=>'required|string','url'=>'required|url','secret'=>'required|string|min:16','events'=>'required|array|min:1']);$d['secret']=\Illuminate\Support\Facades\Crypt::encryptString($d['secret']);$d['events']=json_encode($d['events']);return$this->insert('integration_webhooks',$d);}
 public function storeCompany(Request$r){$d=$this->companyData($r);$d['settings']=json_encode($d['settings']??[]);return$this->insert('companies',$d);}
 public function updateCompany(Request$r,int$id){abort_unless(DB::table('companies')->where('id',$id)->exists(),404);$d=$this->companyData($r,true);if(isset($d['settings']))$d['settings']=json_encode($d['settings']);DB::table('companies')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(DB::table('companies')->find($id));}
 public function storeBranch(Request$r){$d=$r->validate(['company_id'=>'required|exists:companies,id','name'=>'required|string|max:255','code'=>'required|string|max:50|unique:branches,code','address'=>'nullable|string','phone'=>'nullable|string','is_head_office'=>'sometimes|boolean']);return$this->insert('branches',$d);}
 public function updateBranch(Request$r,int$id){$d=$r->validate(['name'=>'sometimes|required|string|max:255','address'=>'nullable|string','phone'=>'nullable|string','is_head_office'=>'sometimes|boolean','is_active'=>'sometimes|boolean']);abort_unless(DB::table('branches')->where('id',$id)->exists(),404);DB::table('branches')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(DB::table('branches')->find($id));}
 private function companyData(Request$r,bool$partial=false):array{$s=$partial?'sometimes|':'';return$r->validate(['name'=>$s.'required|string|max:255','legal_name'=>'nullable|string|max:255','registration_number'=>'nullable|string','tin'=>'nullable|string','bin'=>'nullable|string','currency'=>'sometimes|in:BDT','timezone'=>'sometimes|in:Asia/Dhaka','phone'=>'nullable|string','email'=>'nullable|email','address'=>'nullable|string','is_active'=>'sometimes|boolean','settings'=>'nullable|array','settings.provident_fund_employee_rate'=>'nullable|numeric|min:0|max:100','settings.provident_fund_employer_rate'=>'nullable|numeric|min:0|max:100','settings.gratuity_days_per_year'=>'nullable|numeric|min:0|max:90','settings.standard_work_minutes'=>'nullable|integer|min:1|max:1440','settings.overtime_multiplier'=>'nullable|numeric|min:1|max:5','settings.weekly_off_days'=>'nullable|array']);}
 private function insert(string$t,array$d){$id=DB::table($t)->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table($t)->find($id),201);}
}
