<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TalentLifecycleController extends Controller
{
    public function overview()
    {
        return response()->json([
            'requisitions' => DB::table('job_requisitions')->orderByDesc('id')->limit(50)->get(),
            'candidates' => DB::table('candidates')->orderByDesc('id')->limit(100)->get(),
            'applications' => DB::table('job_applications as a')->join('candidates as c','c.id','=','a.candidate_id')->join('job_requisitions as r','r.id','=','a.job_requisition_id')->select('a.*','c.name as candidate_name','r.title as job_title')->orderByDesc('a.id')->limit(100)->get(),
            'interviews' => DB::table('interviews as i')->join('job_applications as a','a.id','=','i.job_application_id')->join('candidates as c','c.id','=','a.candidate_id')->select('i.*','c.name as candidate_name')->orderByDesc('i.scheduled_at')->limit(50)->get(),
            'onboarding' => DB::table('onboarding_cases as o')->join('employees as e','e.id','=','o.employee_id')->join('users as u','u.id','=','e.user_id')->select('o.*','u.name as employee_name')->orderByDesc('o.id')->limit(50)->get(),
            'onboarding_tasks' => DB::table('onboarding_tasks')->orderByDesc('id')->limit(100)->get(),
            'performance_cycles' => DB::table('performance_cycles')->orderByDesc('id')->limit(30)->get(),
            'performance_goals' => DB::table('performance_goals as g')->join('employees as e','e.id','=','g.employee_id')->join('users as u','u.id','=','e.user_id')->select('g.*','u.name as employee_name')->orderByDesc('g.id')->limit(100)->get(),
            'performance_reviews' => DB::table('performance_reviews as r')->join('employees as e','e.id','=','r.employee_id')->join('users as u','u.id','=','e.user_id')->select('r.*','u.name as employee_name')->orderByDesc('r.id')->limit(100)->get(),
            'training_courses' => DB::table('training_courses')->orderByDesc('id')->limit(50)->get(),
            'training_enrollments' => DB::table('training_enrollments as t')->join('training_courses as c','c.id','=','t.training_course_id')->join('employees as e','e.id','=','t.employee_id')->join('users as u','u.id','=','e.user_id')->select('t.*','c.title','u.name as employee_name')->orderByDesc('t.id')->limit(100)->get(),
            'offboarding' => DB::table('offboarding_cases as o')->join('employees as e','e.id','=','o.employee_id')->join('users as u','u.id','=','e.user_id')->select('o.*','u.name as employee_name')->orderByDesc('o.id')->limit(50)->get(),
            'offboarding_clearances' => DB::table('offboarding_clearances')->orderByDesc('id')->limit(100)->get(),
        ]);
    }
    public function requisitions(Request $r) { return DB::table('job_requisitions')->when($r->status,fn($q,$v)=>$q->where('status',$v))->orderByDesc('id')->paginate(20); }
    public function storeRequisition(Request $r) { $d=$r->validate(['company_id'=>'nullable|exists:companies,id','department_id'=>'required|exists:departments,id','position_id'=>'nullable|exists:positions,id','title'=>'required|string|max:255','vacancies'=>'required|integer|min:1','description'=>'required|string','requirements'=>'nullable|string','salary_min'=>'nullable|numeric|min:0','salary_max'=>'nullable|numeric|gte:salary_min','employment_type'=>'required|in:full-time,part-time,contract,intern','closing_date'=>'nullable|date']);$d['requested_by']=$r->user()->id;return $this->insert('job_requisitions',$d); }
    public function requisitionStatus(Request $r,int $id) { $d=$r->validate(['status'=>'required|in:draft,pending_approval,open,closed,cancelled']);$row=DB::table('job_requisitions')->find($id);abort_unless($row,404);if($d['status']==='open')$d['approved_by']=$r->user()->id;DB::table('job_requisitions')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(['message'=>'Requisition updated']); }

    public function candidates(Request $r) { return DB::table('candidates')->when($r->search,fn($q,$v)=>$q->where(fn($x)=>$x->where('name','like',"%$v%")->orWhere('email','like',"%$v%")))->paginate(20); }
    public function storeCandidate(Request $r) { $d=$r->validate(['name'=>'required|string|max:255','email'=>'required|email|unique:candidates,email','phone'=>'nullable|string|max:30','source'=>'nullable|string|max:100','resume_path'=>'nullable|string','national_id'=>'nullable|string','skills'=>'nullable|array','experience_years'=>'sometimes|numeric|min:0','education'=>'nullable|array']);foreach(['skills','education'] as $k)if(isset($d[$k]))$d[$k]=json_encode($d[$k]);return $this->insert('candidates',$d); }
    public function apply(Request $r) { $d=$r->validate(['job_requisition_id'=>'required|exists:job_requisitions,id','candidate_id'=>'required|exists:candidates,id','assigned_recruiter'=>'nullable|exists:users,id','notes'=>'nullable|string']);$req=DB::table('job_requisitions')->find($d['job_requisition_id']);abort_unless($req->status==='open',422,'Applications require an open requisition');return $this->insert('job_applications',$d); }
    public function applicationStage(Request $r,int $id) { $d=$r->validate(['stage'=>'required|in:applied,screening,shortlisted,interview,offer,hired,rejected,withdrawn','rating'=>'nullable|numeric|min:0|max:5','notes'=>'nullable|string']);abort_unless(DB::table('job_applications')->where('id',$id)->exists(),404);DB::table('job_applications')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(['message'=>'Application stage updated']); }
    public function scheduleInterview(Request $r) { $d=$r->validate(['job_application_id'=>'required|exists:job_applications,id','type'=>'required|in:phone,video,onsite,technical,hr,final','scheduled_at'=>'required|date|after:now','duration_minutes'=>'sometimes|integer|min:15','location_or_link'=>'nullable|string','panel_user_ids'=>'required|array|min:1','panel_user_ids.*'=>'exists:users,id']);return DB::transaction(function()use($d){$panel=$d['panel_user_ids'];unset($d['panel_user_ids']);$id=DB::table('interviews')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);foreach($panel as $i=>$uid)DB::table('interview_panel')->insert(['interview_id'=>$id,'user_id'=>$uid,'is_lead'=>$i===0]);return response()->json(['id'=>$id],201);}); }
    public function interviewResult(Request $r,int $id) { $d=$r->validate(['status'=>'required|in:completed,cancelled,no_show','score'=>'nullable|numeric|min:0|max:100','feedback'=>'nullable|string']);abort_unless(DB::table('interviews')->where('id',$id)->exists(),404);DB::table('interviews')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(['message'=>'Interview updated']); }

    public function startOnboarding(Request $r) { $d=$r->validate(['employee_id'=>'required|exists:employees,id','start_date'=>'required|date','target_completion_date'=>'nullable|date|after_or_equal:start_date','tasks'=>'required|array|min:1','tasks.*.title'=>'required|string','tasks.*.description'=>'nullable|string','tasks.*.assigned_to'=>'nullable|exists:users,id','tasks.*.due_date'=>'nullable|date']);$d['owner_id']=$r->user()->id;return DB::transaction(function()use($d){$tasks=$d['tasks'];unset($d['tasks']);$id=DB::table('onboarding_cases')->insertGetId($d+['status'=>'in_progress','created_at'=>now(),'updated_at'=>now()]);foreach($tasks as $task)DB::table('onboarding_tasks')->insert($task+['onboarding_case_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['id'=>$id],201);}); }
    public function completeOnboardingTask(int $id) { abort_unless(DB::table('onboarding_tasks')->where('id',$id)->exists(),404);DB::table('onboarding_tasks')->where('id',$id)->update(['status'=>'completed','completed_at'=>now(),'updated_at'=>now()]);$caseId=DB::table('onboarding_tasks')->where('id',$id)->value('onboarding_case_id');if(!DB::table('onboarding_tasks')->where('onboarding_case_id',$caseId)->whereNotIn('status',['completed','waived'])->exists())DB::table('onboarding_cases')->where('id',$caseId)->update(['status'=>'completed','updated_at'=>now()]);return response()->json(['message'=>'Task completed']); }

    public function storePerformanceCycle(Request $r) { return $this->insert('performance_cycles',$r->validate(['company_id'=>'nullable|exists:companies,id','name'=>'required|string|max:255','starts_on'=>'required|date','ends_on'=>'required|date|after:starts_on','status'=>'sometimes|in:draft,active,review,closed'])); }
    public function storeGoal(Request $r) { $d=$r->validate(['performance_cycle_id'=>'required|exists:performance_cycles,id','employee_id'=>'required|exists:employees,id','title'=>'required|string','description'=>'nullable|string','weight'=>'required|numeric|min:0.01|max:100','target_value'=>'nullable|numeric']);$cycle=DB::table('performance_cycles')->find($d['performance_cycle_id']);abort_if($cycle->status==='closed',422,'Cycle is closed');return $this->insert('performance_goals',$d); }
    public function storeReview(Request $r) { $d=$r->validate(['performance_cycle_id'=>'required|exists:performance_cycles,id','employee_id'=>'required|exists:employees,id','review_type'=>'required|in:self,manager,peer,hr','score'=>'nullable|numeric|min:0|max:100','ratings'=>'nullable|array','strengths'=>'nullable|string','improvements'=>'nullable|string','comments'=>'nullable|string','status'=>'required|in:draft,submitted,acknowledged']);$d['reviewer_id']=$r->user()->id;if(isset($d['ratings']))$d['ratings']=json_encode($d['ratings']);return $this->insert('performance_reviews',$d); }

    public function storeCourse(Request $r) { return $this->insert('training_courses',$r->validate(['company_id'=>'nullable|exists:companies,id','title'=>'required|string','description'=>'nullable|string','provider'=>'nullable|string','cost'=>'sometimes|numeric|min:0','duration_hours'=>'sometimes|integer|min:0','is_mandatory'=>'sometimes|boolean','valid_until'=>'nullable|date'])); }
    public function enroll(Request $r) { return $this->insert('training_enrollments',$r->validate(['training_course_id'=>'required|exists:training_courses,id','employee_id'=>'required|exists:employees,id'])); }
    public function completeTraining(Request $r,int $id) { $d=$r->validate(['score'=>'nullable|numeric|min:0|max:100','certificate_path'=>'nullable|string','certificate_expires_at'=>'nullable|date']);abort_unless(DB::table('training_enrollments')->where('id',$id)->exists(),404);DB::table('training_enrollments')->where('id',$id)->update($d+['status'=>'completed','completed_at'=>now(),'updated_at'=>now()]);return response()->json(['message'=>'Training completed']); }

    public function startOffboarding(Request $r) { $d=$r->validate(['employee_id'=>'required|exists:employees,id','separation_type'=>'required|in:resignation,termination,retirement,redundancy,death,contract_end','notice_date'=>'required|date','last_working_date'=>'required|date|after_or_equal:notice_date','reason'=>'nullable|string','clearance_areas'=>'required|array|min:1','clearance_areas.*.area'=>'required|string','clearance_areas.*.approver_id'=>'nullable|exists:users,id']);$d['owner_id']=$r->user()->id;return DB::transaction(function()use($d){$areas=$d['clearance_areas'];unset($d['clearance_areas']);$id=DB::table('offboarding_cases')->insertGetId($d+['created_at'=>now(),'updated_at'=>now()]);foreach($areas as $area)DB::table('offboarding_clearances')->insert($area+['offboarding_case_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['id'=>$id],201);}); }
    public function clearance(Request $r,int $id) { $d=$r->validate(['status'=>'required|in:cleared,blocked,waived','notes'=>'nullable|string']);abort_unless(DB::table('offboarding_clearances')->where('id',$id)->exists(),404);$d['cleared_at']=in_array($d['status'],['cleared','waived'])?now():null;DB::table('offboarding_clearances')->where('id',$id)->update($d+['updated_at'=>now()]);return response()->json(['message'=>'Clearance updated']); }

    private function insert(string $table,array $data) { foreach($data as $k=>$v)if(is_array($v))$data[$k]=json_encode($v);$id=DB::table($table)->insertGetId($data+['created_at'=>now(),'updated_at'=>now()]);return response()->json(DB::table($table)->find($id),201); }
}
